services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      
  wizard:
    image: dpage/pgadmin4
    ports:
      - 5050:5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=aldairryan15@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
